FROM rust:1.82
WORKDIR /usr/src/spreebreak_bot
COPY . .
RUN cargo install --path .
ENV RUST_LOG=debug
ENV JUDGE_CHAT_ID {JUDGE_CHAT_ID}
ENV MAINTAINERS {MAINTAINERS}
ENV DATABASE_URL {DATABASE_URL}
ENV TELOXIDE_TOKEN {TELOXIDE_TOKEN}
CMD ["spreebreak_bot"]
